name: ci_docker
on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Github environment to deploy to"
      deployable_branch_name:
        required: true
        type: string
        description: "Name of the branch that will trigger a deployment"
      source_dir_name:
        required: true
        type: string
        description: "Name of the directory, relative to the repo's root, where the directories with source code of the service(s) is located"
      manifest_dir_name:
        required: true
        type: string
        description: "Name of the directory, inside each service, where the manifest files are located"
      custom_service_file_pattern:
        required: true
        type: string
        description: "File pattern, inside each service, to a file that identifies a service as a custom service"
      build_file_pattern:
        required: true
        type: string
        description: "File pattern, inside each service, to a file that identifies a service needing to be built"
      deploy_all_services_label_name:
        required: false
        type: string
        description: "Name of the PR label that signals that all deployable services should be deployed, regardless of changed files"
    outputs:
      img_tag:
        description: "The tag of the pushed images"
        value: ${{ jobs.build-and-push.outputs.IMG_TAG }}

defaults:
  run:
    shell: bash

jobs:
  linter-and-tests:
    uses: ./.github/workflows/linter-tests.yml
    with:
      environment: ${{ inputs.environment }}

  categorize-changed-services:
    needs: linter-and-tests
    if: ${{ (github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true)) && github.ref_name == inputs.deployable_branch_name }}
    uses: ./.github/workflows/categorize-changed-services.yml
    with:
      environment: ${{ inputs.environment }}
      source_dir_name: ${{ inputs.source_dir_name }}
      deployment_file-or-dir_path: ${{ inputs.manifest_dir_name }}
      custom_service_file_pattern: ${{ inputs.custom_service_file_pattern }}
      build_file_pattern: ${{ inputs.build_file_pattern }}
      force_deploy_all_services: ${{ inputs.deploy_all_services_label_name != '' && contains(github.event.pull_request.labels.*.name, inputs.deploy_all_services_label_name) }}

  build-and-push:
    runs-on: ubuntu-latest
    needs: categorize-changed-services
    if: ${{ needs.categorize-changed-services.outputs.SERVICES_TO_BUILD != '' || (vars.NUM_TAGS_TO_KEEP && needs.categorize-changed-services.outputs.SERVICES_TO_REMOVE != '') }}
    environment: ${{ inputs.environment }}
    outputs:
      IMG_TAG: ${{ steps.build-artifacts.outputs.IMG_TAG }}
    steps:
      - name: Clone repo
        uses: actions/checkout@v4

      - name: Build artifacts
        id: build-artifacts
        if: ${{ needs.categorize-changed-services.outputs.SERVICES_TO_BUILD != '' }}
        env:
          SERVICES_TO_BUILD: ${{ needs.categorize-changed-services.outputs.SERVICES_TO_BUILD }}
        run: >-
          SERVICES_TO_BUILD=$(echo "${SERVICES_TO_BUILD}" | tr '[:upper:]' '[:lower:]');
          IMG_TAG=$(git rev-parse --short HEAD);
          
          chmod +x ./cli/build.sh;
          ./cli/build.sh --cicd --tag ${IMG_TAG} --proj ${{ vars.PROJECT_NAME }} ${SERVICES_TO_BUILD};

          echo "IMG_TAG=${IMG_TAG}" >> "$GITHUB_OUTPUT";

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.AZURE_CLIENT_ID }}","clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZURE_TENANT_ID }}"}'

      - name: Push Docker build artifacts
        id: push-docker-build-artifacts
        if: ${{ needs.categorize-changed-services.outputs.SERVICES_TO_BUILD != '' }}
        env:
          SERVICES_TO_BUILD: ${{ needs.categorize-changed-services.outputs.SERVICES_TO_BUILD }}
          IMG_TAG: ${{ steps.build-artifacts.outputs.IMG_TAG }}
        run: >-
          az acr login --name ${{ vars.ACR_NAME }};

          SERVICES_TO_BUILD=$(echo "${SERVICES_TO_BUILD}" | tr '[:upper:]' '[:lower:]');
          for service in ${SERVICES_TO_BUILD[@]}; do
            echo "Pushing '${service}' service";
            IMAGE_NAME="${{ vars.PROJECT_NAME }}_${service}";
            IMAGE_REMOTE_NAME="${{ vars.ACR_NAME }}.azurecr.io/${{ vars.ACR_REPO_NAME }}/${IMAGE_NAME}:${IMG_TAG}";

            docker image tag "${IMAGE_NAME}:${IMG_TAG}" "${IMAGE_REMOTE_NAME}";
            docker push ${IMAGE_REMOTE_NAME};
          done

      - name: Prune container registry
        if: ${{ vars.NUM_TAGS_TO_KEEP }}
        env:
          SERVICES_TO_BUILD: ${{ needs.categorize-changed-services.outputs.SERVICES_TO_BUILD }}
          SERVICES_TO_REMOVE: ${{ needs.categorize-changed-services.outputs.SERVICES_TO_REMOVE }}
        run: >-
          prune_repo () {
            REPO=$1;
            NUM_TAGS_TO_KEEP=$2;

            echo "Processing repo: ${REPO}";

            TAGS=$(az acr repository show-tags --name "${{ vars.ACR_NAME }}" --repository "${REPO}" --orderby time_asc --output json);
            TAGS=($(echo "${TAGS}" | jq -r '.[]')); # Convert JSON into bash array
            echo "Found tags: ${TAGS[@]}";

            if [ ${#TAGS[@]} -gt ${NUM_TAGS_TO_KEEP} ]; then
              TAGS=("${TAGS[@]:0:${#TAGS[@]}-${NUM_TAGS_TO_KEEP}}"); # Remove the newest NUM_TAGS_TO_KEEP tags from the array (using AWK)
              echo "Keeping the ${NUM_TAGS_TO_KEEP} newest tags. Will delete the tags: ${TAGS[@]}";

              for tag in ${TAGS[@]}; do
                echo "Deleting the tag: ${tag}";
                az acr repository delete --name "${{ vars.ACR_NAME }}" --image "${REPO}:${tag}" -y;
              done
            else
              echo "Number of tags below minimum. No need to prune.";
            fi
          }

          SERVICE_REPO_BASE_PATH="${{ vars.ACR_REPO_NAME }}/${{ vars.PROJECT_NAME }}";

          SERVICES_TO_BUILD=$(echo "${SERVICES_TO_BUILD}" | tr '[:upper:]' '[:lower:]');
          for service in ${SERVICES_TO_BUILD[@]}; do
            echo "Checking built service '${service}' for image pruning.";
            prune_repo "${SERVICE_REPO_BASE_PATH}_${service}" ${{ vars.NUM_TAGS_TO_KEEP }};
          done
          
          SERVICES_TO_REMOVE=$(echo "${SERVICES_TO_REMOVE}" | tr '[:upper:]' '[:lower:]');
          for service in ${SERVICES_TO_REMOVE[@]}; do
            echo "Checking removed service '${service}' for image pruning.";
            prune_repo "${SERVICE_REPO_BASE_PATH}_${service}" 0;
          done

      - name: Logout from Azure
        if: always()
        run: >-
          az logout;
